apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tekmetric-backend-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: tekmetric-backend
  namespaceSelector:
    any: true
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
      honorLabels: true