replicaCount: 2


image:
  repository: tekmetric-backend
  tag: "latest"
  pullPolicy: IfNotPresent


service:
  type: ClusterIP
  port: 8080


resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi


livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 20
  failureThreshold: 3


readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3


ingress:
  enabled: false
  hosts:
    - host: tekmetric.local
      paths: [ "/" ]


hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60